### PR TITLE
Add a DateTime Calculator to Examples 

### PR DESCRIPTION
**Pull request by rob-dodson**
This pull request adds another app to the Examples directory. It is a Date/Time calculator that shows off some more methods of the Time package, specifically the differenceInWhole and next/previous methods. I always wanted to be able to do calendar math in a simple app like this. The app can calculate date/time differences between two dates, or it can calculate a new date/time from the start date/time and an offset in years/month/days/hours/seconds. 

Screenshot 2024-03-30 at 11 34 19 AM

(I have not been able to figure out how to add the Time package as "local" as the other Example does.)

### CODE REVIEW

**Comment by davedelong** [comment]
This looks really slick and would be a great addition to the examples project. Would you be willing to fold it into the existing Examples.xcodeproj as a new tab, or would you like me to do that?

**Comment by rob-dodson** [comment]
I would be happy to do it. Should it pick up the timezone and calendar types you have in the other tab?

Also, what are your thoughts on the plusdays calculation in the DifferencesView? It’s just modolo days by 30 to get the extra days in a month.

Rob

**Comment by rob-dodson** [comment]
Moved the calculator to a tab on the Example app.

**Comment by davedelong** [comment]
Thanks @rob-dodson! This will be a great addition. I'll merge this and then push up some tidying to add some cod reuse etc.

**Pull request merged**
